<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <artifactId>rrhh-back-web-digitaldoc-api-rest</artifactId>
  <packaging>jar</packaging>
  <name>rrhh-back-web-digitaldoc-api-rest</name>

  <parent>
    <groupId>com.mercadona.rrhh.digitaldoc</groupId>
    <artifactId>rrhh-back-web-digitaldoc</artifactId>
    <version>1.0.0</version>
    <relativePath>../../pom.xml</relativePath>
  </parent>


  <dependencies>

    <dependency>
      <groupId>com.mercadona.rrhh.digitaldoc</groupId>
      <artifactId>rrhh-back-web-digitaldoc-application</artifactId>
    </dependency>

    <dependency>
      <groupId>com.mercadona.framework.cna</groupId>
      <artifactId>fwkcna-starter-web</artifactId>
    </dependency>

    <dependency>
      <groupId>com.mercadona.framework.cna</groupId>
      <artifactId>fwkcna-starter-security</artifactId>
    </dependency>


    <dependency>
      <groupId>org.springframework.security</groupId>
      <artifactId>spring-security-test</artifactId>
      <scope>test</scope>
    </dependency>

  </dependencies>

  <build>
    <plugins>
      <plugin>
        <groupId>org.openapitools</groupId>
        <artifactId>openapi-generator-maven-plugin</artifactId>
        <version>7.4.0</version>
        <executions>
          <execution>
            <goals>
              <goal>generate</goal>
            </goals>
            <configuration>
              <inputSpec>${project.basedir}/contracts/swagger.yaml</inputSpec>
              <generatorName>spring</generatorName>
              <apiPackage>com.mercadona.rrhh.digitaldoc.definition.server</apiPackage>
              <modelPackage>com.mercadona.rrhh.digitaldoc.model</modelPackage>
              <configOptions>
                <interfaceOnly>true</interfaceOnly>
                <useSpringBoot3>true</useSpringBoot3>
                <useTags>true</useTags>
                <openApiNullable>false</openApiNullable>
                <skipDefaultInterface>true</skipDefaultInterface>
                <sourceFolder>.</sourceFolder>
              </configOptions>
            </configuration>
          </execution>
        </executions>
      </plugin>
    </plugins>
  </build>

</project>
