spring:
  application:
    name: rrhh-back-web-digitaldoc
  cache:
    cache-names: enrichment
    caffeine:
      spec: maximumSize=10000,expireAfterWrite=10m

# Actuator endpoints configuration
management:
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true
  endpoints:
    web:
      exposure:
        include: [ info, health, metrics, prometheus ]


server:
  port: 8080
  servlet:
    context-path: /human-resources/rrhh/digitaldoc/v1
